#!/usr/bin/env python3
"""rig write-back server for the RippleTypeHero Framer port.

Two deliberate differences from a stock rig write-back server:

  1. STRING KNOBS. The stock template only formats int/float props. This target's knob set
     includes three colour props and two text props, so PROPS carries a `kind` of
     "str" alongside "int"/"float".

  2. TWO GATES, NOT ONE. The usual rule for a tuning rig is "never mutate the target component's default
     prop values -- the call site is the contract." A Framer marketplace component has no
     in-repo call site -- the buyer drops an instance on the Framer canvas and the
     component's own defaults ARE what they first see. So Apply here does NOT touch
     defaults. It writes a sidecar + a tuned-props snippet, and promoting a tune into
     `defaultProps` / `addPropertyControls(defaultValue)` is a SEPARATE, explicitly
     requested step. Apply = "I like this tune." Promote = "ship it."

Apply is human-triggered only. Standing up this server writes nothing.
"""
import json, os, threading
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

RIG_DIR = os.path.dirname(os.path.abspath(__file__))
FRAMER_DIR = os.path.dirname(RIG_DIR)
PORT = 8792

TARGET = "RippleTypeHero (Framer port)"
COMPONENT = "RippleTypeHero"
SIDECAR_PATH = os.path.join(FRAMER_DIR, "rig-tunes", "ripple-type-hero.json")
SNIPPET_PATH = os.path.join(FRAMER_DIR, "RippleTypeHero.tuned.tsx")

# (knob-key, jsx-prop, kind)  kind in {"int","float","str"}
PROPS = [
    ("text",        "text",        "str"),
    ("ctaLabel",    "ctaLabel",    "str"),
    ("relief",      "relief",      "float"),
    ("glow",        "glow",        "float"),
    ("caustics",    "caustics",    "int"),
    ("paperColor",  "paperColor",  "str"),
    ("inkColor",    "inkColor",    "str"),
    ("accentColor", "accentColor", "str"),
]

SNIPPET_TEMPLATE = '''// AUTO-GENERATED by the animation rig bench -- tuned CALL-SITE props for {component}.
// Regenerated on every "Apply". Does NOT change the component's own defaults.
//
// For the Framer listing these values still need to be PROMOTED into the component's
// `defaultProps` + `addPropertyControls(... defaultValue)` -- that is a separate,
// explicitly-approved step, not something Apply does. See rig-server.py's header.
import {component} from "./{component}.framer"

export function {component}Tuned() {{
  return (
    <{component}
{props}    />
  )
}}
'''


def fmt(v, kind):
    if kind == "str":
        return '"%s"' % str(v).replace('"', '\\"')
    v = float(v)
    if kind == "int" or v == int(v):
        return "{%d}" % int(v)
    return "{%s}" % repr(round(v, 3))


def write_snippet(k):
    lines = ""
    for key, jsx, kind in PROPS:
        if key not in k:
            continue
        val = fmt(k[key], kind)
        lines += "      %s=%s\n" % (jsx, val)
    with open(SNIPPET_PATH, "w", encoding="utf-8") as f:
        f.write(SNIPPET_TEMPLATE.format(component=COMPONENT, props=lines))


class H(SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=RIG_DIR, **kw)

    def _json(self, code, obj):
        out = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(out)))
        self.end_headers()
        self.wfile.write(out)

    def do_POST(self):
        path = self.path.split("?")[0]
        if path == "/shutdown":                 # UI "Quit" button -> stop the server & exit
            self._json(200, {"ok": True, "stopping": True})
            threading.Thread(target=self.server.shutdown, daemon=True).start()
            return
        if path != "/apply":
            self.send_error(404)
            return
        try:
            n = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(n) or b"{}")
            k = body.get("knob", {})
            wrote = []
            os.makedirs(os.path.dirname(SIDECAR_PATH), exist_ok=True)
            with open(SIDECAR_PATH, "w", encoding="utf-8") as f:
                json.dump(body, f, indent=2)
            wrote.append(SIDECAR_PATH)
            write_snippet(k)
            wrote.append(SNIPPET_PATH)
            self._json(200, {"ok": True, "wrote": [os.path.basename(p) for p in wrote]})
        except Exception as e:
            self._json(500, {"ok": False, "error": str(e)})

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    print("rig write-back server on http://localhost:%d  (target: %s)" % (PORT, TARGET))
    print("IMPORTANT: open the bench at http://localhost:%d/rig-bench.html -- NOT 127.0.0.1." % PORT)
    print("Bench and target must share a host or Chrome throttles the iframe's rAF.")
    ThreadingHTTPServer(("127.0.0.1", PORT), H).serve_forever()
