// AUTO-GENERATED by the animation rig bench -- tuned CALL-SITE props for RippleTypeHero.
// Regenerated on every "Apply". Does NOT change the component's own defaults.
//
// For the Framer listing these values still need to be PROMOTED into the component's
// `defaultProps` + `addPropertyControls(... defaultValue)` -- that is a separate,
// explicitly-approved step, not something Apply does. See rig-server.py's header.
import RippleTypeHero from "./RippleTypeHero.framer"

export function RippleTypeHeroTuned() {
  return (
    <RippleTypeHero
      text="FRAMER"
      ctaLabel="Rain"
      relief={16}
      glow={4.5}
      caustics={110}
      paperColor="#04060A"
      inkColor="#fefefe"
      accentColor="#171717"
    />
  )
}
